# docker-compose.yaml
version: '3'
services:
  node-app:
    image: wanderlust
    container_name: node-app-container
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /usr/src/app
    working_dir: /usr/src/app
    command: npm start
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo-container
    environment:
      ATLAS_URL: ${ATLAS_URL}
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
