# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - WanderrLust

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_228b17d3910b4c239014673018325713 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a07a9efbe0424664b2f4aeed9ac7c34e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_228b17d3910b4c239014673018325713 }}/wanderlust:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WanderrLust'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b29bd173dc9b4435b60aab215439a431 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_228b17d3910b4c239014673018325713 }}/wanderlust:${{ github.sha }}'